import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

interface DatamodelField {
  name: string;
  kind: string;
  type: string;
}

interface DatamodelModel {
  name: string;
  fields: DatamodelField[];
  documentation?: string;
}

export function writeSchema(outputDir: string, models: DatamodelModel[]): void {
  const schemaEntries: string[] = [];
  const modelNames: string[] = [];
  const modelsObjectEntries: string[] = [];

  for (const model of models) {
    modelNames.push(model.name);

    const fieldEntries: string[] = [];
    const fieldKeys: string[] = [];

    for (const field of model.fields) {
      const kind = field.kind === 'scalar' || field.kind === 'enum' ? field.kind : 'object';
      fieldEntries.push(`      ${field.name}: { kind: '${kind}', type: '${field.type}' }`);
      fieldKeys.push(field.name);
    }

    let modelEntry = `  ${model.name}: {\n    fields: {\n${fieldEntries.join(',\n')}\n    }`;
    if (model.documentation) {
      modelEntry += `,\n    documentation: ${JSON.stringify(model.documentation)}`;
    }
    modelEntry += '\n  }';
    schemaEntries.push(modelEntry);

    const fieldTypes = fieldKeys.map((k) => `${k}: true`).join('; ');
    modelsObjectEntries.push(`  ${model.name}: { ${fieldTypes} }`);
  }

  const schemaContent = `// Generated by prisma-select - DO NOT EDIT
import type { Schema } from 'prisma-select';

export const schema = {
${schemaEntries.join(',\n')}
} as const satisfies Schema;

export type ModelName = ${modelNames.map((n) => `'${n}'`).join(' | ')};

export interface ModelsObject {
${modelsObjectEntries.join(';\n')};
}
`;

  writeFileSync(resolve(outputDir, 'schema.ts'), schemaContent, 'utf-8');

  const indexContent = `// Generated by prisma-select - DO NOT EDIT
export { schema } from './schema.js';
export type { ModelName, ModelsObject } from './schema.js';
`;

  writeFileSync(resolve(outputDir, 'index.ts'), indexContent, 'utf-8');
}
